import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import buildClient from '@/api/build-client';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const getServerSideProps = async (context) => {
  const client = buildClient(context);
  const { data } = await client.get('/api/tickets');

  return { props: { tickets: data } };
};

export default function Home({ currentUser, tickets }) {
  const ticketsList = tickets.map((ticket) => {
    return (
      <tr key={ticket.id}>
        <td>{ticket.title}</td>
        <td>{ticket.price}</td>
        <td>
          <Link href={`/tickets/${ticket.id}`}>View</Link>
        </td>
      </tr>
    );
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${inter.className}`}>
        <h1>Tickets</h1>
        <table className="table">
          <thead>
            <tr>
              <th>Title</th>
              <th>Price</th>
            </tr>
          </thead>
          <body>{ticketsList}</body>
        </table>
      </div>
    </>
  );
}
