import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import client from '@/api/build-client';

const inter = Inter({ subsets: ['latin'] });

export const getServerSideProps = async (context) => {
  const { data } = await client(context).get('/api/users/currentuser');

  return { props: { currentUser: data.currentUser } };
};

export default function Home({ currentUser }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {currentUser ? (
          <h1>You are signed in</h1>
        ) : (
          <h1>You are not signed in</h1>
        )}
      </main>
    </>
  );
}
