import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import axios from 'axios';

const inter = Inter({ subsets: ['latin'] });

export const getServerSideProps = async () => {
  const response = await fetch(
    'https://ticketing-duykim.cloud.okteto.net/api/users/currentuser'
  ).then((res) => res.json());

  console.log(response);
  return { props: { currentUser: 'sjd' } };
};

export default function Home({ currentUser }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>{currentUser}</main>
    </>
  );
}
