apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ticketing
  annotations:
    nginx.ingress.kubernetes.io/use-regex: 'true'
    dev.okteto.com/generate-host: 'true'
    dev.okteto.com/endpoints: https://ticketing-${OKTETO_NAMESPACE}.${OKTETO_DOMAIN}
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api/users/?(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-srv
                port:
                  number: 3001
          - path: /api/tickets/?(.*)
            pathType: Prefix
            backend:
              service:
                name: tickets-srv
                port:
                  number: 3002
          - path: /api/orders/?(.*)
            pathType: Prefix
            backend:
              service:
                name: orders-srv
                port:
                  number: 3003
          - path: /api/payments/?(.*)
            pathType: Prefix
            backend:
              service:
                name: payments-srv
                port:
                  number: 3004
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: client-srv
                port:
                  number: 3000
